[package]
name = "gluebuddy"
version = "0.1.0"
authors = ["Levente Polyak <anthraxx@archlinux.org>", "Sven-Hendrik Haase <svenstaro@gmail.com>"]
edition = "2018"

[dependencies]
keycloak = "10"
gitlab = "0.1210"
reqwest = "0.10"
tokio = { version = "0.2", features = ["full"] }
futures = "0.3"
anyhow = "1.0"
log = "0.4"
env_logger = "0.7"
structopt = "0.3"
